version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 3306
    networks:
      - database

  wildfly:
    image: jboss/wildfly:latest
    expose:
      - 8080
      - 9990
    depends_on:
      - mysql
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal-only
      - database

networks:
  internal-only:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  database:
    driver: bridge
