  version: '3'

  services:
    mysql:
      image: mysql:latest
      container_name: votify-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: votify
      ports:
        - "3310:3310"
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - votify-main-network   

    votify-app:
      image: cyrilmuchiri/votify-v2:ultimate
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        MYSQL_HOST: mysql
        MYSQL_PORT: 3310
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: votify
      networks:
        - votify-main-network  

  volumes:
    mysql-data:
  networks:
    votify-main-network:
      driver: bridge  