# apiVersion: v1
# kind: Service
# metadata:
#   name: votify-service
# spec:
#   selector:
#     app: mysqld
#   ports:
#   - protocol: TCP
#     port: 3306
#     targetPort: 3306
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: votify-app-service
spec:
  selector:
    app: votify-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000  # Choose any available port number
