- name: Deploy Docker containers
  hosts: web
  become: yes
  tasks:
    - name: Create the working directory
      file:
        path: /home/chief/votify-v2
        state: directory

    - name: Copy Docker Compose file 
      copy:
        src: staging-docker-compose.yml 
        dest: /home/chief/votify-v2/staging-docker-compose.yml  
        # remote_src: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: true

    - name: Install Docker and Docker-Compose
      apt:
        pkg:
          - docker
          - docker-ce
          - docker-compose
        state: latest
        update_cache: yes
      become: true

    - name: Run Docker Compose
      command: nohup docker-compose -f staging-docker-compose.yml up -d
      args:
        chdir: /home/chief/votify-v2

