apiVersion: apps/v1
kind: Deployment
metadata:
  name: votify-app
  labels:
    app: votify-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votify-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: votify-app
    spec:
      containers:
      - name: votify-app
        image: cyrilmuchiri/votify-v2:ultimate
    
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1Gi"
      restartPolicy: Always
