spring.application.name=votify-v2
# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/votify
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specify the driver class name (optional for modern Spring Boot as it's auto-detecte