version: 2.1

executors:
  docker-publisher:
    docker:
      - image: cimg/openjdk:17.0.9-node

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.9-node
    steps:
      - checkout
      - run:
          name: Run Maven Tests
          command: mvn test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t cyrilmuchiri/votify-staging:staging -f staging-Dockerfile .
      - persist_to_workspace:
          root: .
          paths:
            - ./staging-Dockerfile
            - ./image.tar

  publish-latest:
    docker:
      - image: cimg/openjdk:17.0.9-node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push cyrilmuchiri/votify-staging:staging

  publish-tag:
    docker:
      - image: cimg/openjdk:17.0.9-node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push cyrilmuchiri/votify-staging:staging
            docker tag cyrilmuchiri/votify-staging:staging cyrilmuchiri/votify-staging:${CIRCLE_TAG/v/''}
            docker push cyrilmuchiri/votify-staging:${CIRCLE_TAG/v/''}

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install -y ansible
      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"
      - run:
          name: Deploy with Ansible
          command: |
            ansible-playbook -i inventory.ini staging-playbook.yml

workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: staging
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy:
          requires:
            - publish-latest
          filters:
            branches:
              only: staging

  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - publish-tag
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
