version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: cyrilmuchiri/votify-v2
    docker:
      - image: cimg/openjdk:17.0.9-node

jobs:
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:ultimate $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:ultimate
            docker push $IMAGE_NAME:$IMAGE_TAG

  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:ultimate $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:ultimate
            docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install -y ansible

      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"
      - run:
          name: Deploy with Ansible
          command: |
            ansible-playbook -i inventory.ini playbook.yml

workflows:
  version: 2
  publish-and-deploy:
    jobs:
      - publish-latest
      - publish-tag:
          requires:
            - publish-latest
      - deploy:
          requires:
            - publish-tag
